# Generated by Django 3.0.3 on 2020-05-27 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activityperiod',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='tz',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('activityperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.ActivityPeriod')),
            ],
            options={
                'unique_together': {('activityperiod', 'start_time', 'end_time')},
            },
        ),
    ]
