# Generated by Django 3.0.3 on 2020-05-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_auto_20200527_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='activityperiod',
            field=models.ManyToManyField(related_name='activity_period', to='api1.ActivityPeriod'),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='period',
            name='activityperiod',
        ),
    ]
