# Generated by Django 3.0.3 on 2020-05-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_auto_20200527_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='activityperiod',
            field=models.ManyToManyField(related_name='activity_period', to='api1.ActivityPeriod'),
        ),
    ]
